steps:
- name: 'gcr.io/cloud-builders/docker'
  - name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/machine-translation-tf/github.com/Nielspace/machine-translation-tf:$SHORT_SHA', '.']

